upstreams:
  - name: camera1
    rtspUrl: rtsp://localhost:8554/stream1
  - rtspUrl: rtsp://localhost:8554/stream2
  - name: usbCamera
    sourceType: usb
    device: default
    codec: h264
    frameRate: 30
